<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cargo_comision extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cargo_comision_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Listing of cargo_comision
     */
    function index()
    {
        if($this->acceso(23)) {
            $data['cargo_comision'] = $this->Cargo_comision_model->get_all_cargo_comision();

            $data['_view'] = 'cargo_comision/index';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Adding a new cargo_comision
     */
    function add()
    {
        if($this->acceso(23)) {
            $this->load->library('form_validation');
            $this->form_validation->set_rules('cargocomision_descripcion','Cargo Nombre','trim|required', array('required' => 'Este Campo no debe ser vacio'));
            if($this->form_validation->run())
            {
                $params = array(
                    'cargocomision_descripcion' => $this->input->post('cargocomision_descripcion'),
                    'cargocomision_nivel' => $this->input->post('cargocomision_nivel'),
                );
                $cargocomision_id = $this->Cargo_comision_model->add_cargo_comision($params);
                redirect('cargo_comision/index');
            }
            else
            {            
                $data['_view'] = 'cargo_comision/add';
                $this->load->view('layouts/main',$data);
            }
        }
    }  

    /*
     * Editing a cargo_comision
     */
    function edit($cargocomision_id)
    {
        if($this->acceso(23)) {
            // check if the cargo_comision exists before trying to edit it
            $data['cargo_comision'] = $this->Cargo_comision_model->get_cargo_comision($cargocomision_id);
            if(isset($data['cargo_comision']['cargocomision_id']))
            {
                $this->load->library('form_validation');
                $this->form_validation->set_rules('cargocomision_descripcion','Cargo Nombre','trim|required', array('required' => 'Este Campo no debe ser vacio'));
                if($this->form_validation->run())     
                {   
                    $params = array(
                        'cargocomision_descripcion' => $this->input->post('cargocomision_descripcion'),
                        'cargocomision_nivel' => $this->input->post('cargocomision_nivel'),
                    );
                    $this->Cargo_comision_model->update_cargo_comision($cargocomision_id,$params);
                    redirect('cargo_comision/index');
                }
                else
                {
                    $data['_view'] = 'cargo_comision/edit';
                    $this->load->view('layouts/main',$data);
                }
            }
            else
                show_error('The cargo_comision you are trying to edit does not exist.');
        }
    }
    
    /* obtiene todos los cargos comision */
    function get_cargo_comision()
    {
        //if($this->acceso(103)) {
            if ($this->input->is_ajax_request()) {
                $datos = $this->Cargo_comision_model->get_all_cargo_comision();
                echo json_encode($datos);
            }else{                 
                show_404();
            }
        //}
    }
    
    /* registra cargo comision */
    function registrar_cargo_comision()
    {
        //if($this->acceso(103)) {
            if ($this->input->is_ajax_request()) {
                $comisionadmin_id = $this->input->post('comisionadmin_id');
                $params = array(
                    'cargocomision_id' => $this->input->post('cargocomision_id'),
                );
                $this->load->model('Comision_administrativo_model');
                $this->Comision_administrativo_model->update_comisionadmin_decargocomision($comisionadmin_id,$params); 
                
                echo json_encode("ok");
            }else{                 
                show_404();
            }
        //}
    }
}
