<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Comision_administrativo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Comision_administrativo_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }

    /* busca administrativos que pertenecen a una comisión */
    function get_administrativos()
    {
        //if($this->acceso(103)) {
            if($this->input->is_ajax_request()){
                $comision_id = $this->input->post('comision_id');
                $datos = $this->Comision_administrativo_model->get_all_comisionadministrativo($comision_id);
                echo json_encode($datos);
            }else{                 
                show_404();
            }
        //}
    }
    
}
