<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Compromiso extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Compromiso_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Listing of compromiso
     */
    function index()
    {
        if($this->acceso(11)) {
            $data['compromiso'] = $this->Compromiso_model->get_all_compromiso();

            $data['_view'] = 'compromiso/index';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Adding a new compromiso
     */
    /*function add()
    {
        if($this->acceso(12)) {
            $this->load->library('form_validation');
            $this->form_validation->set_rules('compromiso_descripcion','Gestion Descripcion','trim|required', array('required' => 'Este Campo no debe ser vacio'));
            $this->form_validation->set_rules('compromiso_fechainicio','Gestion Fechainicio','required');
            if($this->form_validation->run())     
            {
                $estado_id = 9;
                $params = array(
                    'estado_id' => $estado_id,
                    'compromiso_fechainicio' => $this->input->post('compromiso_fechainicio'),
                    'compromiso_descripcion' => $this->input->post('compromiso_descripcion'),
                    'compromiso_fechafin' => $this->input->post('compromiso_fechafin'),
                );
                $compromiso_id = $this->Compromiso_model->add_compromiso($params);
                redirect('compromiso/index');
            }else{
                $data['_view'] = 'compromiso/add';
                $this->load->view('layouts/main',$data);
            }
        }
    }*/

    /*
     * Editing a compromiso
     */
    /*function edit($compromiso_id)
    {
        if($this->acceso(13)) {
            // check if the compromiso exists before trying to edit it
            $data['compromiso'] = $this->Compromiso_model->get_compromiso($compromiso_id);

            if(isset($data['compromiso']['compromiso_id']))
            {
                $this->load->library('form_validation');
                $this->form_validation->set_rules('compromiso_fechainicio','Gestion Fechainicio','required');
                $this->form_validation->set_rules('compromiso_descripcion','Gestion Descripcion','required');
                if($this->form_validation->run())
                {
                    $params = array(
                        'estado_id' => $this->input->post('estado_id'),
                        'compromiso_fechainicio' => $this->input->post('compromiso_fechainicio'),
                        'compromiso_descripcion' => $this->input->post('compromiso_descripcion'),
                        'compromiso_fechafin' => $this->input->post('compromiso_fechafin'),
                    );

                    $this->Compromiso_model->update_compromiso($compromiso_id,$params);            
                    redirect('compromiso/index');
                }
                else
                {
                    $this->load->model('Estado_model');
                    $tipo = 4;
                    $data['all_estado'] = $this->Estado_model->get_tipo_estado($tipo);
                    
                    $data['_view'] = 'compromiso/edit';
                    $this->load->view('layouts/main',$data);
                }
            }
            else
                show_error('The compromiso you are trying to edit does not exist.');
        }
    }*/

    /*
     * Deleting compromiso
     */
    /*function remove($compromiso_id)
    {
        $compromiso = $this->Compromiso_model->get_compromiso($compromiso_id);

        // check if the compromiso exists before trying to delete it
        if(isset($compromiso['compromiso_id']))
        {
            $this->Compromiso_model->delete_compromiso($compromiso_id);
            redirect('compromiso/index');
        }
        else
            show_error('The compromiso you are trying to delete does not exist.');
    }*/
    
    /* registrar compromiso */
    function registrar_compromiso()
    {
        //if($this->acceso(103)) {
            if($this->input->is_ajax_request()){
                //$para_guardar = $this->input->post('para_guardar');
                $fechahora = date("Y-m-d H:i:s");
                $estado_id = 9;
                $params = array(
                    'postulante_id' => $this->input->post('postulante_id'),
                    'estado_id' => $estado_id,
                    'compromiso_fechahora' => $fechahora,
                    'compromiso_compromiso' => $this->input->post('para_guardar'),
                );
                $compromiso_id = $this->Compromiso_model->add_compromiso($params);
                echo json_encode("ok");
            }else{                 
                show_404();
            }
        //}
    }
    /*
     * muestra un compromiso
     */
    function mostrarcompromiso($compromiso_id)
    {
        if($this->acceso(11)) {
            $data['compromiso'] = $this->Compromiso_model->get_compromiso($compromiso_id);

            $data['_view'] = 'compromiso/mostrarcompromiso';
            $this->load->view('layouts/main',$data);
        }
    }
}
