<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dube extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Dube_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Listing of dube
     */
    function index()
    {
        if($this->acceso(35)) {
            $data['dube'] = $this->Dube_model->get_all_dube();

            $data['_view'] = 'dube/index';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Adding a new dube
     */
    function add()
    {
        if($this->acceso(35)) {
            if(isset($_POST) && count($_POST) > 0)     
            {
                /* *********************INICIO imagen***************************** */
                $foto="";
                if (!empty($_FILES['dube_organigrama']['name'])){

                    $this->load->library('image_lib');
                    $config['upload_path'] = './resources/images/organigrama/';
                    $img_full_path = $config['upload_path'];

                    //$config['allowed_types'] = 'gif|jpeg|jpg|png';
                    $config['allowed_types'] = '*';
                    $config['image_library'] = 'gd2';
                    $config['max_size'] = 0;
                    $config['max_width'] = 0;
                    $config['max_height'] = 0;

                    $new_name = time(); //str_replace(" ", "_", $this->input->post('proveedor_nombre'));
                    $config['file_name'] = $new_name; //.$extencion;
                    $config['file_ext_tolower'] = TRUE;

                    $this->load->library('upload', $config);
                    $this->upload->do_upload('dube_organigrama');

                    $img_data = $this->upload->data();
                    $extension = $img_data['file_ext'];
                    /* ********************INICIO para resize***************************** */
                    if ($img_data['file_ext'] == ".jpg" || $img_data['file_ext'] == ".png" || $img_data['file_ext'] == ".jpeg" || $img_data['file_ext'] == ".gif") {
                        $conf['image_library'] = 'gd2';
                        $conf['source_image'] = $img_data['full_path'];
                        $conf['new_image'] = './resources/images/organigrama/';
                        $conf['maintain_ratio'] = TRUE;
                        $conf['create_thumb'] = FALSE;
                        $conf['width'] = 800;
                        $conf['height'] = 600;
                        $this->image_lib->clear();
                        $this->image_lib->initialize($conf);
                        if(!$this->image_lib->resize()){
                            echo $this->image_lib->display_errors('','');
                        }
                        $confi['image_library'] = 'gd2';
                        $confi['source_image'] = './resources/images/organigrama/'.$new_name.$extension;
                        $confi['new_image'] = './resources/images/organigrama/'."thumb_".$new_name.$extension;
                        $confi['create_thumb'] = FALSE;
                        $confi['maintain_ratio'] = TRUE;
                        $confi['width'] = 100;
                        $confi['height'] = 100;

                        $this->image_lib->clear();
                        $this->image_lib->initialize($confi);
                        $this->image_lib->resize();
                    }
                    /* ********************F I N  para resize***************************** */


                    $foto = $new_name.$extension;
                }
                /* *********************FIN imagen***************************** */
                
                $params = array(
                    'dube_autoridadades' => $this->input->post('dube_autoridadades'),
                    'dube_organigrama' => $foto,
                    'dube_mision' => $this->input->post('dube_mision'),
                    'dube_vision' => $this->input->post('dube_vision'),
                    'dube_objetivo' => $this->input->post('dube_objetivo'),
                );

                $dube_id = $this->Dube_model->add_dube($params);
                redirect('dube/index');
            }
            else
            {            
                $data['_view'] = 'dube/add';
                $this->load->view('layouts/main',$data);
            }
        }
    }  

    /*
     * Editing a dube
     */
    function edit($dube_id)
    {
        if($this->acceso(35)) {
            // check if the dube exists before trying to edit it
            $data['dube'] = $this->Dube_model->get_dube($dube_id);

            if(isset($data['dube']['dube_id']))
            {
                if(isset($_POST) && count($_POST) > 0)     
                {
                    /* *********************INICIO imagen************************* */
                    $foto="";
                        $foto1= $this->input->post('dube_organigrama1');
                    if (!empty($_FILES['dube_organigrama']['name']))
                    {
                        $this->load->library('image_lib');
                        $config['upload_path'] = './resources/images/organigrama/';
                        //$config['allowed_types'] = 'gif|jpeg|jpg|png';
                        $config['allowed_types'] = '*';
                        $config['max_size'] = 0;
                        $config['max_width'] = 0;
                        $config['max_height'] = 0;

                        $new_name = time();
                        $config['file_name'] = $new_name; //.$extencion;
                        $config['file_ext_tolower'] = TRUE;

                        $this->load->library('upload', $config);
                        $this->upload->do_upload('dube_organigrama');

                        $img_data = $this->upload->data();
                        $extension = $img_data['file_ext'];
                        /* ********************INICIO para resize***************************** */
                        if($img_data['file_ext'] == ".jpg" || $img_data['file_ext'] == ".png" || $img_data['file_ext'] == ".jpeg" || $img_data['file_ext'] == ".gif") {
                            $conf['image_library'] = 'gd2';
                            $conf['source_image'] = $img_data['full_path'];
                            $conf['new_image'] = './resources/images/organigrama/';
                            $conf['maintain_ratio'] = TRUE;
                            $conf['create_thumb'] = FALSE;
                            $conf['width'] = 800;
                            $conf['height'] = 600;
                            $this->image_lib->clear();
                            $this->image_lib->initialize($conf);
                            if(!$this->image_lib->resize()){
                                echo $this->image_lib->display_errors('','');
                            }

                            $confi['image_library'] = 'gd2';
                            $confi['source_image'] = './resources/images/organigrama/'.$new_name.$extension;
                            $confi['new_image'] = './resources/images/organigrama/'."thumb_".$new_name.$extension;
                            $confi['create_thumb'] = FALSE;
                            $confi['maintain_ratio'] = TRUE;
                            $confi['width'] = 100;
                            $confi['height'] = 100;

                            $this->image_lib->clear();
                            $this->image_lib->initialize($confi);
                            $this->image_lib->resize();
                        }
                        /* ********************F I N  para resize***************************** */
                        //$directorio = base_url().'resources/imagenes/';
                        $directorio = FCPATH.'resources\images\organigrama\\';
                        //$directorio = $_SERVER['DOCUMENT_ROOT'].'/ximpleman_web/resources/images/productos/';
                        if(isset($foto1) && !empty($foto1)){
                          if(file_exists($directorio.$foto1)){
                              unlink($directorio.$foto1);
                              $mimagenthumb = "thumb_".$foto1;
                              //$mimagenthumb = str_replace(".", "_thumb.", $foto1);
                              if($img_data['file_ext'] == ".jpg" || $img_data['file_ext'] == ".png" || $img_data['file_ext'] == ".jpeg" || $img_data['file_ext'] == ".gif") {
                                  unlink($directorio.$mimagenthumb);
                              }
                          }
                      }
                        $foto = $new_name.$extension;
                    }else{
                        $foto = $foto1;
                    }
                    
                    $params = array(
                        'dube_autoridadades' => $this->input->post('dube_autoridadades'),
                        'dube_organigrama' => $foto,
                        'dube_mision' => $this->input->post('dube_mision'),
                        'dube_vision' => $this->input->post('dube_vision'),
                        'dube_objetivo' => $this->input->post('dube_objetivo'),
                    );

                    $this->Dube_model->update_dube($dube_id,$params);            
                    redirect('dube/index');
                }
                else
                {
                    $data['_view'] = 'dube/edit';
                    $this->load->view('layouts/main',$data);
                }
            }
            else
                show_error('The dube you are trying to edit does not exist.');
        }
    } 

    /*
     * Deleting dube
     */
    /*function remove($dube_id)
    {
        $dube = $this->Dube_model->get_dube($dube_id);

        // check if the dube exists before trying to delete it
        if(isset($dube['dube_id']))
        {
            $this->Dube_model->delete_dube($dube_id);
            redirect('dube/index');
        }
        else
            show_error('The dube you are trying to delete does not exist.');
    }*/
    
}
