<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estudiante extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Estudiante_model');
    } 

    /*
     * Listing of estudiante
     */
    function index()
    {
        $data['estudiante'] = $this->Estudiante_model->get_all_estudiante();
        
        $data['_view'] = 'estudiante/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new estudiante
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('estudiante_nombre','Estudiante Nombre','required');
		$this->form_validation->set_rules('estudiante_apellidos','Estudiante Apellidos','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'estudiante_nombre' => $this->input->post('estudiante_nombre'),
				'estudiante_apellidos' => $this->input->post('estudiante_apellidos'),
				'estudiante_ci' => $this->input->post('estudiante_ci'),
				'estudiante_email' => $this->input->post('estudiante_email'),
				'estudiante_carrera' => $this->input->post('estudiante_carrera'),
				'estudiante_celular' => $this->input->post('estudiante_celular'),
				'estudiante_telefono' => $this->input->post('estudiante_telefono'),
				'estudiante_codsis' => $this->input->post('estudiante_codsis'),
            );
            
            $estudiante_id = $this->Estudiante_model->add_estudiante($params);
            redirect('estudiante/index');
        }
        else
        {            
            $data['_view'] = 'estudiante/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a estudiante
     */
    function edit($estudiante_id)
    {   
        // check if the estudiante exists before trying to edit it
        $data['estudiante'] = $this->Estudiante_model->get_estudiante($estudiante_id);
        
        if(isset($data['estudiante']['estudiante_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('estudiante_nombre','Estudiante Nombre','required');
			$this->form_validation->set_rules('estudiante_apellidos','Estudiante Apellidos','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'estudiante_nombre' => $this->input->post('estudiante_nombre'),
					'estudiante_apellidos' => $this->input->post('estudiante_apellidos'),
					'estudiante_ci' => $this->input->post('estudiante_ci'),
					'estudiante_email' => $this->input->post('estudiante_email'),
					'estudiante_carrera' => $this->input->post('estudiante_carrera'),
					'estudiante_celular' => $this->input->post('estudiante_celular'),
					'estudiante_telefono' => $this->input->post('estudiante_telefono'),
					'estudiante_codsis' => $this->input->post('estudiante_codsis'),
                );

                $this->Estudiante_model->update_estudiante($estudiante_id,$params);            
                redirect('estudiante/index');
            }
            else
            {
                $data['_view'] = 'estudiante/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The estudiante you are trying to edit does not exist.');
    } 

    /*
     * Deleting estudiante
     */
    function remove($estudiante_id)
    {
        $estudiante = $this->Estudiante_model->get_estudiante($estudiante_id);

        // check if the estudiante exists before trying to delete it
        if(isset($estudiante['estudiante_id']))
        {
            $this->Estudiante_model->delete_estudiante($estudiante_id);
            redirect('estudiante/index');
        }
        else
            show_error('The estudiante you are trying to delete does not exist.');
    }
    
}
