<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Formulario_autentificacion extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Formulario_autentificacion_model');
    } 

    /*
     * Listing of formulario_autentificacion
     */
    function index()
    {
        $data['formulario_autentificacion'] = $this->Formulario_autentificacion_model->get_all_formulario_autentificacion();
        
        $data['_view'] = 'formulario_autentificacion/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new formulario_autentificacion
     */
    /*function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'convoreq_id' => $this->input->post('convoreq_id'),
				'postulante_id' => $this->input->post('postulante_id'),
				'estado_id' => $this->input->post('estado_id'),
				'formulario_requisito' => $this->input->post('formulario_requisito'),
				'formulario_observacion' => $this->input->post('formulario_observacion'),
            );
            
            $formulario_autentificacion_id = $this->Formulario_autentificacion_model->add_formulario_autentificacion($params);
            redirect('formulario_autentificacion/index');
        }
        else
        {
			$this->load->model('Convocatoria_requisito_model');
			$data['all_convocatoria_requisito'] = $this->Convocatoria_requisito_model->get_all_convocatoria_requisito();

			$this->load->model('Postulante_model');
			$data['all_postulante'] = $this->Postulante_model->get_all_postulante();

			$this->load->model('Estado_model');
			$data['all_estado'] = $this->Estado_model->get_all_estado();
            
            $data['_view'] = 'formulario_autentificacion/add';
            $this->load->view('layouts/main',$data);
        }
    }*/

    /*
     * Editing a formulario_autentificacion
     */
    /*function edit($formulario_id)
    {   
        // check if the formulario_autentificacion exists before trying to edit it
        $data['formulario_autentificacion'] = $this->Formulario_autentificacion_model->get_formulario_autentificacion($formulario_id);
        
        if(isset($data['formulario_autentificacion']['formulario_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'convoreq_id' => $this->input->post('convoreq_id'),
					'postulante_id' => $this->input->post('postulante_id'),
					'estado_id' => $this->input->post('estado_id'),
					'formulario_requisito' => $this->input->post('formulario_requisito'),
					'formulario_observacion' => $this->input->post('formulario_observacion'),
                );

                $this->Formulario_autentificacion_model->update_formulario_autentificacion($formulario_id,$params);            
                redirect('formulario_autentificacion/index');
            }
            else
            {
				$this->load->model('Convocatoria_requisito_model');
				$data['all_convocatoria_requisito'] = $this->Convocatoria_requisito_model->get_all_convocatoria_requisito();

				$this->load->model('Postulante_model');
				$data['all_postulante'] = $this->Postulante_model->get_all_postulante();

				$this->load->model('Estado_model');
				$data['all_estado'] = $this->Estado_model->get_all_estado();

                $data['_view'] = 'formulario_autentificacion/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The formulario_autentificacion you are trying to edit does not exist.');
    }*/

    /*
     * Deleting formulario_autentificacion
     */
    /*function remove($formulario_id)
    {
        $formulario_autentificacion = $this->Formulario_autentificacion_model->get_formulario_autentificacion($formulario_id);

        // check if the formulario_autentificacion exists before trying to delete it
        if(isset($formulario_autentificacion['formulario_id']))
        {
            $this->Formulario_autentificacion_model->delete_formulario_autentificacion($formulario_id);
            redirect('formulario_autentificacion/index');
        }
        else
            show_error('The formulario_autentificacion you are trying to delete does not exist.');
    }*/
    
}
