<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Postulante extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Postulante_model');
    } 

    /*
     * Listing of postulante
     */
    function index()
    {
        $data['postulante'] = $this->Postulante_model->get_all_postulante_estudiante();
        
        $data['_view'] = 'postulante/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new postulante
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {
            $estado = 1;
            $params = array(
                'estado_id' => $estado,
                'estudiante_id' => $this->input->post('estudiante_id'),
                'plaza_id' => $this->input->post('plaza_id'),
                'padres_tutores' => $this->input->post('padres_tutores'),
                'postulante_observacion' => $this->input->post('postulante_observacion'),
                'postulante_correccion' => $this->input->post('postulante_correccion'),
            );
            
            $postulante_id = $this->Postulante_model->add_postulante($params);
            redirect('postulante/index');
        }
        else
        {
            /*$this->load->model('Estado_model');
            $data['all_estado'] = $this->Estado_model->get_all_estado();
            */
            $this->load->model('Estudiante_model');
            $data['all_estudiante'] = $this->Estudiante_model->get_all_estudiante();

            $this->load->model('Plazas_beca_model');
            $data['all_plazas_becas'] = $this->Plazas_beca_model->get_all_plazas_becas();
            
            $data['_view'] = 'postulante/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a postulante
     */
    function edit($postulante_id)
    {   
        // check if the postulante exists before trying to edit it
        $data['postulante'] = $this->Postulante_model->get_postulante($postulante_id);
        
        if(isset($data['postulante']['postulante_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'estado_id' => $this->input->post('estado_id'),
					'estudiante_id' => $this->input->post('estudiante_id'),
					'plaza_id' => $this->input->post('plaza_id'),
					'padres_tutores' => $this->input->post('padres_tutores'),
					'postulante_observacion' => $this->input->post('postulante_observacion'),
					'postulante_correccion' => $this->input->post('postulante_correccion'),
                );

                $this->Postulante_model->update_postulante($postulante_id,$params);            
                redirect('postulante/index');
            }
            else
            {
				$this->load->model('Estado_model');
				$data['all_estado'] = $this->Estado_model->get_all_estado();

				$this->load->model('Estudiante_model');
				$data['all_estudiante'] = $this->Estudiante_model->get_all_estudiante();

				$this->load->model('Plazas_beca_model');
				$data['all_plazas_becas'] = $this->Plazas_beca_model->get_all_plazas_becas();

                $data['_view'] = 'postulante/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The postulante you are trying to edit does not exist.');
    } 

    /*
     * Deleting postulante
     */
    function remove($postulante_id)
    {
        $postulante = $this->Postulante_model->get_postulante($postulante_id);

        // check if the postulante exists before trying to delete it
        if(isset($postulante['postulante_id']))
        {
            $this->Postulante_model->delete_postulante($postulante_id);
            redirect('postulante/index');
        }
        else
            show_error('The postulante you are trying to delete does not exist.');
    }
    
}
