<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Publicacion extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Publicacion_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Listing of publicacion
     */
    function index()
    {
        if($this->acceso(20)) {
            $data['publicacion'] = $this->Publicacion_model->get_all_publicacion();

            $data['_view'] = 'publicacion/index';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Adding a new publicacion
     */
    function add()
    {
        if($this->acceso(21)) {
            $this->load->library('form_validation');
            $this->form_validation->set_rules('publicacion_fecha','Publicacion Fecha','required');
            if($this->form_validation->run())     
            {
                $estado = 1;
                $params = array(
                    'dube_id' => $this->input->post('dube_id'),
                    'beca_id' => $this->input->post('beca_id'),
                    'estado_id' => $estado,
                    'publicacion_fecha' => $this->input->post('publicacion_fecha'),
                    'publicacion_autor' => $this->input->post('publicacion_autor'),
                    'publicacion_enlace' => $this->input->post('publicacion_enlace'),
                    'publicacion_texto' => $this->input->post('publicacion_texto'),
                );

                $publicacion_id = $this->Publicacion_model->add_publicacion($params);
                redirect('publicacion/index');
            }
            else
            {
                $this->load->model('Dube_model');
                $data['all_dube'] = $this->Dube_model->get_all_dube();

                $this->load->model('Beca_model');
                $data['all_beca'] = $this->Beca_model->get_all_beca();

                /*$this->load->model('Estado_model');
                $data['all_estado'] = $this->Estado_model->get_all_estado();
                */

                $data['_view'] = 'publicacion/add';
                $this->load->view('layouts/main',$data);
            }
        }
    }  

    /*
     * Editing a publicacion
     */
    function edit($publicacion_id)
    {
        if($this->acceso(22)) {
            // check if the publicacion exists before trying to edit it
            $data['publicacion'] = $this->Publicacion_model->get_publicacion($publicacion_id);
            if(isset($data['publicacion']['publicacion_id']))
            {
                $this->load->library('form_validation');
                $this->form_validation->set_rules('publicacion_fecha','Publicacion Fecha','required');
                if($this->form_validation->run())
                {   
                    $params = array(
                        'dube_id' => $this->input->post('dube_id'),
                        'beca_id' => $this->input->post('beca_id'),
                        'estado_id' => $this->input->post('estado_id'),
                        'publicacion_fecha' => $this->input->post('publicacion_fecha'),
                        'publicacion_autor' => $this->input->post('publicacion_autor'),
                        'publicacion_enlace' => $this->input->post('publicacion_enlace'),
                        'publicacion_texto' => $this->input->post('publicacion_texto'),
                    );

                    $this->Publicacion_model->update_publicacion($publicacion_id,$params);            
                    redirect('publicacion/index');
                }
                else
                {
                    $this->load->model('Dube_model');
                    $data['all_dube'] = $this->Dube_model->get_all_dube();

                    $this->load->model('Beca_model');
                    $data['all_beca'] = $this->Beca_model->get_all_beca();

                    $this->load->model('Estado_model');
                    $data['all_estado'] = $this->Estado_model->get_all_estado();

                    $data['_view'] = 'publicacion/edit';
                    $this->load->view('layouts/main',$data);
                }
            }
            else
                show_error('The publicacion you are trying to edit does not exist.');
        }
    }

    /*
     * Deleting publicacion
     */
    /*function remove($publicacion_id)
    {
        $publicacion = $this->Publicacion_model->get_publicacion($publicacion_id);

        // check if the publicacion exists before trying to delete it
        if(isset($publicacion['publicacion_id']))
        {
            $this->Publicacion_model->delete_publicacion($publicacion_id);
            redirect('publicacion/index');
        }
        else
            show_error('The publicacion you are trying to delete does not exist.');
    }*/
    
}
