<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reporte extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Reporte_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }

    /* reporte de solicitud de unidades! */
    function rep_sunidad()
    {
        if($this->acceso(36)) {
            $this->load->model('Gestion_model');
            $data['all_gestion'] = $this->Gestion_model->get_all_gestion();

            $this->load->model('Unidad_model');
            $data['all_unidad'] = $this->Unidad_model->get_all_unidad();
            $data['_view'] = 'reporte/rep_sunidad';
            $this->load->view('layouts/main',$data);
        }
    }
    /* reporte de solicitud de unidades */
    function buscar_sunidad()
    {
        if ($this->input->is_ajax_request()) {
            $gestion_id = $this->input->post('gestion_id');
            $unidad_id = $this->input->post('unidad_id');
            $datos = $this->Reporte_model->get_all_solicitud_unidad($gestion_id, $unidad_id);
            echo json_encode($datos);
        }else{
            show_404();
        }
    }
    
}
