<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Seguimiento extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Seguimiento_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }

    /* seguimiento a postulante */
    function seguimiento($postulante_id)
    {
        if($this->acceso(14)){
            //$rolusuario = $this->session_data['rol'];
            //$data['ver_requisitos'] = $rolusuario[19-1]['rolusuario_asignado'];
            $this->load->model('Postulante_model');
            $data['postulante'] = $this->Postulante_model->get_thispostulante($postulante_id);
            if($data['postulante']['beca_id'] == 9){
                $this->load->model('Solunidad_postulante_model');
                $data['solicitud_unidadpostulante'] = $this->Solunidad_postulante_model->esreg_solunidad_postulante($postulante_id);
            }else{
                $data['solicitud_unidadpostulante'] = "";
            }
            $data['seguimientos'] = $this->Seguimiento_model->get_seguimientos($postulante_id);

            $data['_view'] = 'seguimiento/seguimiento';
            $this->load->view('layouts/main',$data);
        }
    }
    function add($postulante_id)
    {
        if($this->acceso(15)){
            $data['postulante_id'] = $postulante_id;
            $this->load->model('Postulante_model');
            $data['postulante'] = $this->Postulante_model->get_thispostulante($postulante_id);
            if(isset($_POST) && count($_POST) > 0)     
            {
                /* *********************INICIO imagen***************************** */
                $foto="";
                if (!empty($_FILES['seguimiento_respaldo']['name'])){

                    $this->load->library('image_lib');
                    $config['upload_path'] = './resources/images/seguimiento/';
                    $img_full_path = $config['upload_path'];

                    //$config['allowed_types'] = 'gif|jpeg|jpg|png';
                    $config['allowed_types'] = '*';
                    $config['image_library'] = 'gd2';
                    $config['max_size'] = 0;
                    $config['max_width'] = 0;
                    $config['max_height'] = 0;

                    $new_name = time(); //str_replace(" ", "_", $this->input->post('proveedor_nombre'));
                    $config['file_name'] = $new_name; //.$extencion;
                    $config['file_ext_tolower'] = TRUE;

                    $this->load->library('upload', $config);
                    $this->upload->do_upload('seguimiento_respaldo');

                    $img_data = $this->upload->data();
                    $extension = $img_data['file_ext'];
                    /* ********************INICIO para resize***************************** */
                    if ($img_data['file_ext'] == ".jpg" || $img_data['file_ext'] == ".png" || $img_data['file_ext'] == ".jpeg" || $img_data['file_ext'] == ".gif") {
                        $conf['image_library'] = 'gd2';
                        $conf['source_image'] = $img_data['full_path'];
                        $conf['new_image'] = './resources/images/seguimiento/';
                        $conf['maintain_ratio'] = TRUE;
                        $conf['create_thumb'] = FALSE;
                        $conf['width'] = 800;
                        $conf['height'] = 600;
                        $this->image_lib->clear();
                        $this->image_lib->initialize($conf);
                        if(!$this->image_lib->resize()){
                            echo $this->image_lib->display_errors('','');
                        }
                        $confi['image_library'] = 'gd2';
                        $confi['source_image'] = './resources/images/seguimiento/'.$new_name.$extension;
                        $confi['new_image'] = './resources/images/seguimiento/'."thumb_".$new_name.$extension;
                        $confi['create_thumb'] = FALSE;
                        $confi['maintain_ratio'] = TRUE;
                        $confi['width'] = 100;
                        $confi['height'] = 100;

                        $this->image_lib->clear();
                        $this->image_lib->initialize($confi);
                        $this->image_lib->resize();
                    }
                    /* ********************F I N  para resize***************************** */


                    $foto = $new_name.$extension;
                }
                /* *********************FIN imagen***************************** */
                $fecha = date("Y-m-d");
                $hora  = date("H:i:s");
                $params = array(
                    'postulante_id' => $postulante_id,
                    'beca_id' => $data['postulante']['beca_id'],
                    'seguimiento_descripcion' => $this->input->post('seguimiento_descripcion'),
                    'seguimiento_fecha' => $fecha,
                    'seguimiento_hora' => $hora,
                    'seguimiento_mes' => $this->input->post('seguimiento_mes'),
                    'seguimiento_gestion' => $this->input->post('seguimiento_gestion'),
                    'seguimiento_respaldo' => $foto,
                );

                $seguimiento_id = $this->Seguimiento_model->add_seguimiento($params);
                redirect('seguimiento/seguimiento/'.$postulante_id);
            }else{
                /*$this->load->model('Gestion_model');
                $data['all_gestion'] = $this->Gestion_model->get_all_gestion();
                */
                $data['_view'] = 'seguimiento/add';
                $this->load->view('layouts/main',$data);
            }
        }
    }

    /*
     * Editing a seguimiento
     */
    function edit($seguimiento_id)
    {
        if($this->acceso(16)){
            // check if the postulante exists before trying to edit it
            $data['seguimiento'] = $this->Seguimiento_model->get_seguimiento($seguimiento_id);
            /*print_r($data['seguimiento']);
            break;*/
            if(isset($data['seguimiento']['seguimiento_id']))
            {
                $postulante_id = $data['seguimiento']['postulante_id'];
                $data['postulante_id'] = $postulante_id;
                $this->load->model('Postulante_model');
                $data['postulante'] = $this->Postulante_model->get_thispostulante($postulante_id);
                if(isset($_POST) && count($_POST) > 0)     
                {
                    /* *********************INICIO imagen***************************** */
                    $foto="";
                        $foto1= $this->input->post('seguimiento_respaldo1');
                    if (!empty($_FILES['seguimiento_respaldo']['name']))
                    {
                        $this->load->library('image_lib');
                        $config['upload_path'] = './resources/images/seguimiento/';
                        //$config['allowed_types'] = 'gif|jpeg|jpg|png';
                        $config['allowed_types'] = '*';
                        $config['max_size'] = 0;
                        $config['max_width'] = 0;
                        $config['max_height'] = 0;

                        $new_name = time();
                        $config['file_name'] = $new_name; //.$extencion;
                        $config['file_ext_tolower'] = TRUE;

                        $this->load->library('upload', $config);
                        $this->upload->do_upload('seguimiento_respaldo');

                        $img_data = $this->upload->data();
                        $extension = $img_data['file_ext'];
                        /* ********************INICIO para resize***************************** */
                        if($img_data['file_ext'] == ".jpg" || $img_data['file_ext'] == ".png" || $img_data['file_ext'] == ".jpeg" || $img_data['file_ext'] == ".gif") {
                            $conf['image_library'] = 'gd2';
                            $conf['source_image'] = $img_data['full_path'];
                            $conf['new_image'] = './resources/images/seguimiento/';
                            $conf['maintain_ratio'] = TRUE;
                            $conf['create_thumb'] = FALSE;
                            $conf['width'] = 800;
                            $conf['height'] = 600;
                            $this->image_lib->clear();
                            $this->image_lib->initialize($conf);
                            if(!$this->image_lib->resize()){
                                echo $this->image_lib->display_errors('','');
                            }

                            $confi['image_library'] = 'gd2';
                            $confi['source_image'] = './resources/images/seguimiento/'.$new_name.$extension;
                            $confi['new_image'] = './resources/images/seguimiento/'."thumb_".$new_name.$extension;
                            $confi['create_thumb'] = FALSE;
                            $confi['maintain_ratio'] = TRUE;
                            $confi['width'] = 100;
                            $confi['height'] = 100;

                            $this->image_lib->clear();
                            $this->image_lib->initialize($confi);
                            $this->image_lib->resize();
                        }
                        /* ********************F I N  para resize***************************** */
                        //$directorio = base_url().'resources/imagenes/';
                        $directorio = FCPATH.'resources\images\seguimiento\\';
                        if(isset($foto1) && !empty($foto1)){
                          if(file_exists($directorio.$foto1)){
                              unlink($directorio.$foto1);
                              $mimagenthumb = "thumb_".$foto1;
                              //$mimagenthumb = str_replace(".", "_thumb.", $foto1);
                              if($img_data['file_ext'] == ".jpg" || $img_data['file_ext'] == ".png" || $img_data['file_ext'] == ".jpeg" || $img_data['file_ext'] == ".gif") {
                                  unlink($directorio.$mimagenthumb);
                              }
                          }
                      }
                        $foto = $new_name.$extension;
                    }else{
                        $foto = $foto1;
                    }
                    /* *********************FIN imagen***************************** */
                    $params = array(
                        'seguimiento_descripcion' => $this->input->post('seguimiento_descripcion'),
                        'seguimiento_fecha' => $this->input->post('seguimiento_fecha'),
                        'seguimiento_hora' => $this->input->post('seguimiento_hora'),
                        'seguimiento_mes' => $this->input->post('seguimiento_mes'),
                        'seguimiento_gestion' => $this->input->post('seguimiento_gestion'),
                        'seguimiento_respaldo' => $foto,
                    );
                    
                    $this->Seguimiento_model->update_seguimiento($seguimiento_id,$params);            
                    redirect('seguimiento/seguimiento/'.$postulante_id);
                }
                else
                {
                    /*$this->load->model('Gestion_model');
                    $data['all_gestion'] = $this->Gestion_model->get_all_gestion();
                    */
                    $data['_view'] = 'seguimiento/edit';
                    $this->load->view('layouts/main',$data);
                }
            }
            else
                show_error('The postulante you are trying to edit does not exist.');
        }
    }
    
    /*
     * guardar caracterisitca del postualnte que postulo a beca (deporte o cultura)
     */
    function guardarcarac($postulante_id)
    {
        if($this->acceso(16)){
            $this->load->model('Postulante_model');
            $data['postulante'] = $this->Postulante_model->get_thispostulante($postulante_id);
            if(isset($data['postulante']['postulante_id']))
            {
                if(isset($_POST) && count($_POST) > 0)     
                {
                    $params = array(
                        'postulante_caracteristica' => $this->input->post('postulante_caracteristica'),
                    );
                    $this->Postulante_model->update_postulante($postulante_id,$params);            
                    redirect('seguimiento/seguimiento/'.$postulante_id);
                }else{
                    redirect('seguimiento/seguimiento/'.$postulante_id);
                }
            }
            else
                show_error('El postulante que intentas registrar no existe');
        }
    }
}
