<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Solicitud_unidad extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Solicitud_unidad_model');
    } 

    /*
     * Listing of solicitud_unidades
     */
    function index()
    {
        $data['solicitud_unidades'] = $this->Solicitud_unidad_model->get_all_solicitud_unidad();
        
        $data['_view'] = 'solicitud_unidad/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new solicitud_unidad
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                'gestion_id' => $this->input->post('gestion_id'),
                'unidad_id' => $this->input->post('unidad_id'),
                'solicitud_unidad' => $this->input->post('solicitud_unidad'),
                'solicitud_modalidad' => $this->input->post('solicitud_modalidad'),
                'solicitud_cantidad_becarios' => $this->input->post('solicitud_cantidad_becarios'),
                'solicitud_carreras_requiremiento' => $this->input->post('solicitud_carreras_requiremiento'),
                'solicitud_actividad' => $this->input->post('solicitud_actividad'),
            );
            
            $solicitud_unidad_id = $this->Solicitud_unidad_model->add_solicitud_unidad($params);
            redirect('solicitud_unidad/index');
        }
        else
        {
            $this->load->model('Gestion_model');
            $data['all_gestion'] = $this->Gestion_model->get_all_gestion();
            
            $this->load->model('Unidad_model');
            $data['all_unidad'] = $this->Unidad_model->get_all_unidad();
            
            $data['_view'] = 'solicitud_unidad/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a solicitud_unidad
     */
    function edit($solicitud_id)
    {   
        // check if the solicitud_unidad exists before trying to edit it
        $data['solicitud_unidad'] = $this->Solicitud_unidad_model->get_solicitud_unidad($solicitud_id);
        
        if(isset($data['solicitud_unidad']['solicitud_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                    'gestion_id' => $this->input->post('gestion_id'),
                    'unidad_id' => $this->input->post('unidad_id'),
                    'solicitud_unidad' => $this->input->post('solicitud_unidad'),
                    'solicitud_modalidad' => $this->input->post('solicitud_modalidad'),
                    'solicitud_cantidad_becarios' => $this->input->post('solicitud_cantidad_becarios'),
                    'solicitud_carreras_requiremiento' => $this->input->post('solicitud_carreras_requiremiento'),
                    'solicitud_actividad' => $this->input->post('solicitud_actividad'),
                );

                $this->Solicitud_unidad_model->update_solicitud_unidad($solicitud_id,$params);            
                redirect('solicitud_unidad/index');
            }
            else
            {
                $this->load->model('Gestion_model');
                $data['all_gestion'] = $this->Gestion_model->get_all_gestion();

                $this->load->model('Unidad_model');
                $data['all_unidad'] = $this->Unidad_model->get_all_unidad();
                
                $data['_view'] = 'solicitud_unidad/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The solicitud_unidad you are trying to edit does not exist.');
    } 

    /*
     * Deleting solicitud_unidad
     */
    function remove($solicitud_id)
    {
        $solicitud_unidad = $this->Solicitud_unidad_model->get_solicitud_unidad($solicitud_id);

        // check if the solicitud_unidad exists before trying to delete it
        if(isset($solicitud_unidad['solicitud_id']))
        {
            $this->Solicitud_unidad_model->delete_solicitud_unidad($solicitud_id);
            redirect('solicitud_unidad/index');
        }
        else
            show_error('The solicitud_unidad you are trying to delete does not exist.');
    }
    
}
