<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Website extends CI_Controller{
    function __construct()
    {
        parent::__construct();
    }            

    function index()
    {
        $this->load->model('Convocatoria_model');
        $data['las_convocatorias'] = $this->Convocatoria_model->getall_convocatoria_abierto();
        $data['num_convocatorias'] = $this->Convocatoria_model->getall_convocatorias_abiertas();
        $this->load->model('Requisito_model');
        $data['los_requisitos'] = $this->Requisito_model->get_all_requisitoactivo();
        $this->load->model('Beca_model');
        $data['las_becas'] = $this->Beca_model->getall_becas_abiertas();
        $this->load->model('Publicacion_model');
        $data['las_publicaciones'] = $this->Publicacion_model->getall_publicaciones_abiertas();
        $this->load->model('Dube_model');
        $dube_id = 1;
        $data['dube'] = $this->Dube_model->get_dube($dube_id);
        $data['_view'] = 'website';
//        $this->load->view('layouts/login',$data);
        $this->load->view('web/index',$data);
    }
    function masconvocatoria()
    {
        $this->load->model('Convocatoria_model');
        $data['mas_convocatorias'] = $this->Convocatoria_model->getall_convocatorias_abiertas();
        //$data['_view'] = 'web/masconvocatoria';
        //$data['_view'] = 'website';
        $this->load->view('web/masconvocatoria',$data);
    }
    
}
