<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Administrativo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get administrativo by admin_id
     */
    function get_administrativo($admin_id)
    {
        return $this->db->get_where('administrativo',array('admin_id'=>$admin_id))->row_array();
    }
        
    /*
     * Get all administrativo
     */
    function get_all_administrativo()
    {
        $administrativo = $this->db->query("
            SELECT
                a.*, c.cargo_nombre, du.direccionuniv_nombre, e.estado_descripcion, e.estado_color
            FROM
                `administrativo` a
            left join cargo c on a.cargo_id = c.cargo_id
            left join direccion_universitaria du on a.direccionuniv_id = du.direccionuniv_id
            left join estado e on a.estado_id = e.estado_id
            WHERE
                1 = 1

            ORDER BY `admin_id` DESC
        ")->result_array();

        return $administrativo;
    }
        
    /*
     * function to add new administrativo
     */
    function add_administrativo($params)
    {
        $this->db->insert('administrativo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update administrativo
     */
    function update_administrativo($admin_id,$params)
    {
        $this->db->where('admin_id',$admin_id);
        return $this->db->update('administrativo',$params);
    }
    
    /*
     * function to delete administrativo
     */
    function delete_administrativo($admin_id)
    {
        return $this->db->delete('administrativo',array('admin_id'=>$admin_id));
    }
}
