<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Autoridad_contrato_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get autoridad_contrato by autoridadc_id
     */
    function get_autoridad_contrato($autoridadc_id)
    {
        $autoridad_contrato = $this->db->query("
            SELECT
                ac.*, e.estado_descripcion, e.estado_color, g.gestion_descripcion
            FROM
                `autoridad_contrato` ac
            left join estado e on ac.estado_id = e.estado_id
            left join gestion g on ac.gestion_id = g.gestion_id
            WHERE ac.autoridadc_id = $autoridadc_id
        ")->row_array();
        return $autoridad_contrato;
    }
        
    /*
     * Get all autoridad_contrato
     */
    function get_all_autoridad_contrato()
    {
        $autoridad_contrato = $this->db->query("
            SELECT
                ac.*, e.estado_descripcion, e.estado_color, g.gestion_descripcion
            FROM
                `autoridad_contrato` ac
            left join estado e on ac.estado_id = e.estado_id
            left join gestion g on ac.gestion_id = g.gestion_id
            ORDER BY ac.`autoridadc_orden` asc
        ")->result_array();
        return $autoridad_contrato;
    }
        
    /*
     * function to add new autoridad_contrato
     */
    function add_autoridad_contrato($params)
    {
        $this->db->insert('autoridad_contrato',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update autoridad_contrato
     */
    function update_autoridad_contrato($autoridadc_id,$params)
    {
        $this->db->where('autoridadc_id',$autoridadc_id);
        return $this->db->update('autoridad_contrato',$params);
    }
    
    /*
     * function to delete autoridad_contrato
     */
    function delete_autoridad_contrato($autoridadc_id)
    {
        return $this->db->delete('autoridad_contrato',array('autoridadc_id'=>$autoridadc_id));
    }
        function get_autoridad_orden($orden)
    {
        $autoridad_contrato = $this->db->query("
            SELECT
                ac.*
            FROM
                `autoridad_contrato` ac
            WHERE ac.autoridadc_orden = $orden
                and ac.estado_id = 9
        ")->row_array();
        return $autoridad_contrato;
    }
}
