<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Beca_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get beca by beca_id
     */
    function get_beca($beca_id)
    {
        return $this->db->get_where('beca',array('beca_id'=>$beca_id))->row_array();
    }
        
    /*
     * Get all beca
     */
    function get_all_beca()
    {
        $beca = $this->db->query("
            SELECT
                b.*, e.estado_descripcion, e.estado_color
            FROM
                `beca` b
            left join estado e on b.estado_id = e.estado_id
            WHERE
                1 = 1

            ORDER BY `beca_id` DESC
        ")->result_array();

        return $beca;
    }
        
    /*
     * function to add new beca
     */
    function add_beca($params)
    {
        $this->db->insert('beca',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update beca
     */
    function update_beca($beca_id,$params)
    {
        $this->db->where('beca_id',$beca_id);
        return $this->db->update('beca',$params);
    }
    
    /*
     * function to delete beca
     */
    function delete_beca($beca_id)
    {
        return $this->db->delete('beca',array('beca_id'=>$beca_id));
    }
    /*
     * Get all becas abiertas
     */
    function getall_becas_abiertas()
    {
        $beca = $this->db->query("
            SELECT
                b.*, e.estado_descripcion, e.estado_color
            FROM
                `beca` b
            left join estado e on b.estado_id = e.estado_id
            WHERE
                b.estado_id = 1

            ORDER BY `beca_nombre` ASC
        ")->result_array();

        return $beca;
    }
}
