<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cargo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cargo by cargo_id
     */
    function get_cargo($cargo_id)
    {
        return $this->db->get_where('cargo',array('cargo_id'=>$cargo_id))->row_array();
    }
        
    /*
     * Get all cargo
     */
    function get_all_cargo()
    {
        $this->db->order_by('cargo_id', 'desc');
        return $this->db->get('cargo')->result_array();
    }
        
    /*
     * function to add new cargo
     */
    function add_cargo($params)
    {
        $this->db->insert('cargo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cargo
     */
    function update_cargo($cargo_id,$params)
    {
        $this->db->where('cargo_id',$cargo_id);
        return $this->db->update('cargo',$params);
    }
    
    /*
     * function to delete cargo
     */
    function delete_cargo($cargo_id)
    {
        return $this->db->delete('cargo',array('cargo_id'=>$cargo_id));
    }
}
