<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cargo_comision_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cargo by cargocomision_id
     */
    function get_cargo_comision($cargocomision_id)
    {
        return $this->db->get_where('cargo_comision',array('cargocomision_id'=>$cargocomision_id))->row_array();
    }
        
    /*
     * Get all cargo_comision
     */
    function get_all_cargo_comision()
    {
        $this->db->order_by('cargocomision_nivel', 'asc');
        return $this->db->get('cargo_comision')->result_array();
    }
        
    /*
     * function to add new cargo_comision
     */
    function add_cargo_comision($params)
    {
        $this->db->insert('cargo_comision',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cargo_comision
     */
    function update_cargo_comision($cargocomision_id,$params)
    {
        $this->db->where('cargocomision_id',$cargocomision_id);
        return $this->db->update('cargo_comision',$params);
    }
}
