<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Comision_postulante_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get comision_postulante by comisionpost_id
     */
    function get_comision_postulante($comisionpost_id)
    {
        return $this->db->get_where('comision_postulante',array('comisionpost_id'=>$comisionpost_id))->row_array();
    }
        
    /*
     * Get all comision_postulante
     */
    function get_all_comision_postulante()
    {
        $postulante = $this->db->query("
            SELECT
                cp.*, e.estudiante_nombre, e.estudiante_apellidos, c.comision_nombre
            FROM
                `comision_postulante` cp
            left join comision c on cp.comision_id = c.comision_id
            left join postulante p on cp.postulante_id = p.postulante_id
            left join estudiante e on p.estudiante_id = e.estudiante_id
            WHERE
                1 = 1

            ORDER BY e.`estudiante_apellidos` asc, e.`estudiante_nombre` asc
        ")->result_array();

        return $postulante;
    }
        
    /*
     * function to add new comision_postulante
     */
    function add_comision_postulante($params)
    {
        $this->db->insert('comision_postulante',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update comision_postulante
     */
    function update_comision_postulante($comisionpost_id,$params)
    {
        $this->db->where('comisionpost_id',$comisionpost_id);
        return $this->db->update('comision_postulante',$params);
    }
    
    /*
     * function to delete comision_postulante
     */
    function delete_comision_postulante($comisionpost_id)
    {
        return $this->db->delete('comision_postulante',array('comisionpost_id'=>$comisionpost_id));
    }
}
