<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Contrato_Model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get contrato by contrato_id
     */
    function get_contrato($contrato_id)
    {
        return $this->db->get_where('contrato',array('contrato_id'=>$contrato_id))->row_array();
    }
        
    /*
     * Get all contrato
     */
    function get_all_contrato()
    {
        $contrato = $this->db->query("
            SELECT
                c.*, e.estado_descripcion, e.estado_color
            FROM
                `contrato` c
            left join estado e on c.estado_id = e.estado_id
            ORDER BY c.`contrato_id` DESC
        ")->result_array();

        return $contrato;
    }
        
    /*
     * function to add new contrato
     */
    function add_contrato($params)
    {
        $this->db->insert('contrato',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update contrato
     */
    function update_contrato($contrato_id,$params)
    {
        $this->db->where('contrato_id',$contrato_id);
        return $this->db->update('contrato',$params);
    }
    
    /*
     * function to delete contrato
     */
    function delete_contrato($contrato_id)
    {
        return $this->db->delete('contrato',array('contrato_id'=>$contrato_id));
    }
}
