<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Convocatoria_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get convocatoria by convocatoria_id
     */
    function get_convocatoria($convocatoria_id)
    {
        $convocatoria = $this->db->query("
            SELECT
                c.*, pb.plaza_id, pb.plaza_cantidad
            FROM
                convocatoria as c
            left join plazas_becas as pb on c.convocatoria_id = pb.convocatoria_id
            WHERE
                c.convocatoria_id = $convocatoria_id
        ")->row_array();
        return $convocatoria;
    }
        
    /*
     * Get all convocatoria
     */
    function get_all_convocatoria()
    {
        $convocatoria = $this->db->query("
            SELECT
                c.*, g.gestion_descripcion, e.estado_descripcion, e.estado_color, pb.plaza_cantidad
            FROM
                convocatoria as c
            left join gestion as g on c.gestion_id = g.gestion_id
            left join estado as e on c.estado_id = e.estado_id
            left join plazas_becas as pb on c.convocatoria_id = pb.convocatoria_id
            ORDER BY c.convocatoria_id desc
        ")->result_array();
        return $convocatoria;
    }
        
    /*
     * function to add new convocatoria
     */
    function add_convocatoria($params)
    {
        $this->db->insert('convocatoria',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update convocatoria
     */
    function update_convocatoria($convocatoria_id,$params)
    {
        $this->db->where('convocatoria_id',$convocatoria_id);
        return $this->db->update('convocatoria',$params);
    }
    
    /*
     * function to delete convocatoria
     */
    function delete_convocatoria($convocatoria_id)
    {
        return $this->db->delete('convocatoria',array('convocatoria_id'=>$convocatoria_id));
    }
}
