<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Convocatoria_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get convocatoria by convocatoria_id
     */
    function get_convocatoria($convocatoria_id)
    {
        return $this->db->get_where('convocatoria',array('convocatoria_id'=>$convocatoria_id))->row_array();
    }
        
    /*
     * Get all convocatoria
     */
    function get_all_convocatoria()
    {
        $this->db->select('c.*, g.gestion_descripcion, e.estado_descripcion, e.estado_color');
        $this->db->from('convocatoria as c');
        $this->db->join('gestion as g','c.gestion_id = g.gestion_id');
        $this->db->join('estado as e','c.estado_id = e.estado_id');
        $this->db->order_by('convocatoria_id', 'desc');
        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new convocatoria
     */
    function add_convocatoria($params)
    {
        $this->db->insert('convocatoria',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update convocatoria
     */
    function update_convocatoria($convocatoria_id,$params)
    {
        $this->db->where('convocatoria_id',$convocatoria_id);
        return $this->db->update('convocatoria',$params);
    }
    
    /*
     * function to delete convocatoria
     */
    function delete_convocatoria($convocatoria_id)
    {
        return $this->db->delete('convocatoria',array('convocatoria_id'=>$convocatoria_id));
    }
}
