<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dube_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get dube by dube_id
     */
    function get_dube($dube_id)
    {
        return $this->db->get_where('dube',array('dube_id'=>$dube_id))->row_array();
    }
        
    /*
     * Get all dube
     */
    function get_all_dube()
    {
        $this->db->order_by('dube_id', 'desc');
        return $this->db->get('dube')->result_array();
    }
        
    /*
     * function to add new dube
     */
    function add_dube($params)
    {
        $this->db->insert('dube',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update dube
     */
    function update_dube($dube_id,$params)
    {
        $this->db->where('dube_id',$dube_id);
        return $this->db->update('dube',$params);
    }
    
    /*
     * function to delete dube
     */
    function delete_dube($dube_id)
    {
        return $this->db->delete('dube',array('dube_id'=>$dube_id));
    }
}
