<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estado_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estado by estado_id
     */
    function get_estado($estado_id)
    {
        return $this->db->get_where('estado',array('estado_id'=>$estado_id))->row_array();
    }
        
    /*
     * Get all estado
     */
    function get_all_estado()
    {
        $this->db->order_by('estado_id', 'desc');
        return $this->db->get('estado')->result_array();
    }
        
    /*
     * function to add new estado
     */
    function add_estado($params)
    {
        $this->db->insert('estado',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update estado
     */
    function update_estado($estado_id,$params)
    {
        $this->db->where('estado_id',$estado_id);
        return $this->db->update('estado',$params);
    }
    
    /*
     * function to delete estado
     */
    function delete_estado($estado_id)
    {
        return $this->db->delete('estado',array('estado_id'=>$estado_id));
    }
    /* devuelve el tipo de estado */
    function get_tipo_estado($tipo)
    {
        $sql = "SELECT * FROM estado WHERE estado_tipo = ".$tipo;
        $estado = $this->db->query($sql)->result_array();
        return $estado;
    }
}
