<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Estudiante_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estudiante by estudiante_id
     */
    function get_estudiante($estudiante_id)
    {
        return $this->db->get_where('estudiante',array('estudiante_id'=>$estudiante_id))->row_array();
    }
        
    /*
     * Get all estudiante
     */
    function get_all_estudiante()
    {
        $estudiante = $this->db->query("
            SELECT
                e.*
            FROM
                `estudiante` e
            WHERE
                1 = 1

            ORDER BY `e`.`estudiante_apellidos` asc, `e`.`estudiante_nombre` asc
        ")->result_array();

        return $estudiante;
        
        
        $this->db->order_by('estudiante_nombre', 'asc');
        return $this->db->get('estudiante')->result_array();
    }
        
    /*
     * function to add new estudiante
     */
    function add_estudiante($params)
    {
        $this->db->insert('estudiante',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update estudiante
     */
    function update_estudiante($estudiante_id,$params)
    {
        $this->db->where('estudiante_id',$estudiante_id);
        return $this->db->update('estudiante',$params);
    }
    
    /*
     * function to delete estudiante
     */
    function delete_estudiante($estudiante_id)
    {
        return $this->db->delete('estudiante',array('estudiante_id'=>$estudiante_id));
    }
}
