<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Formulario_autentificacion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get formulario_autentificacion by formulario_id
     */
    function get_formulario_autentificacion($formulario_id)
    {
        return $this->db->get_where('formulario_autentificacion',array('formulario_id'=>$formulario_id))->row_array();
    }
        
    /*
     * Get all formulario_autentificacion
     */
    function get_all_formulario_autentificacion()
    {
        $this->db->order_by('formulario_id', 'desc');
        return $this->db->get('formulario_autentificacion')->result_array();
    }
        
    /*
     * function to add new formulario_autentificacion
     */
    function add_formulario_autentificacion($params)
    {
        $this->db->insert('formulario_autentificacion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update formulario_autentificacion
     */
    function update_formulario_autentificacion($formulario_id,$params)
    {
        $this->db->where('formulario_id',$formulario_id);
        return $this->db->update('formulario_autentificacion',$params);
    }
    
    /*
     * function to delete formulario_autentificacion
     */
    function delete_formulario_autentificacion($formulario_id)
    {
        return $this->db->delete('formulario_autentificacion',array('formulario_id'=>$formulario_id));
    }
}
