<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Plazas_beca_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get plazas_beca by plaza_id
     */
    function get_plazas_beca($plaza_id)
    {
        return $this->db->get_where('plazas_becas',array('plaza_id'=>$plaza_id))->row_array();
    }
        
    /*
     * Get all plazas_becas
     */
    function get_all_plazas_becas()
    {
        $plazas = $this->db->query("
            SELECT
                pb.*, b.beca_nombre, c.convocatoria_descripcion
            FROM
                `plazas_becas` pb
            left join beca b on pb.beca_id = b.beca_id
            left join convocatoria c on pb.convocatoria_id = c.convocatoria_id
            WHERE
                1 = 1
            ORDER BY b.beca_nombre ASC
        ")->result_array();
        return $plazas;
    }
        
    /*
     * function to add new plazas_beca
     */
    function add_plazas_beca($params)
    {
        $this->db->insert('plazas_becas',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update plazas_beca
     */
    function update_plazas_beca($plaza_id,$params)
    {
        $this->db->where('plaza_id',$plaza_id);
        return $this->db->update('plazas_becas',$params);
    }
    
    /*
     * function to delete plazas_beca
     */
    function delete_plazas_beca($plaza_id)
    {
        return $this->db->delete('plazas_becas',array('plaza_id'=>$plaza_id));
    }
}
