<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Plazas_beca_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get plazas_beca by plaza_id
     */
    function get_plazas_beca($plaza_id)
    {
        return $this->db->get_where('plazas_becas',array('plaza_id'=>$plaza_id))->row_array();
    }
        
    /*
     * Get all plazas_becas
     */
    function get_all_plazas_becas()
    {
        $this->db->order_by('plaza_id', 'desc');
        return $this->db->get('plazas_becas')->result_array();
    }
        
    /*
     * function to add new plazas_beca
     */
    function add_plazas_beca($params)
    {
        $this->db->insert('plazas_becas',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update plazas_beca
     */
    function update_plazas_beca($plaza_id,$params)
    {
        $this->db->where('plaza_id',$plaza_id);
        return $this->db->update('plazas_becas',$params);
    }
    
    /*
     * function to delete plazas_beca
     */
    function delete_plazas_beca($plaza_id)
    {
        return $this->db->delete('plazas_becas',array('plaza_id'=>$plaza_id));
    }
}
