<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Postulante_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get postulante by postulante_id
     */
    function get_postulante($postulante_id)
    {
        return $this->db->get_where('postulante',array('postulante_id'=>$postulante_id))->row_array();
    }
        
    /*
     * Get all postulante
     */
    function get_all_postulante()
    {
        $this->db->order_by('postulante_id', 'desc');
        return $this->db->get('postulante')->result_array();
    }
        
    /*
     * function to add new postulante
     */
    function add_postulante($params)
    {
        $this->db->insert('postulante',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update postulante
     */
    function update_postulante($postulante_id,$params)
    {
        $this->db->where('postulante_id',$postulante_id);
        return $this->db->update('postulante',$params);
    }
    
    /*
     * function to delete postulante
     */
    function delete_postulante($postulante_id)
    {
        return $this->db->delete('postulante',array('postulante_id'=>$postulante_id));
    }
    /*
     * Get all postulante y nombre del postulante
     */
    function get_all_postulante_estudiante()
    {
        $postulante = $this->db->query("
            SELECT
                p.*, e.estudiante_nombre, e.estudiante_apellidos, pl.plaza_cantidad,
                es.estado_color, es.estado_descripcion
            FROM
                `postulante` p
            left join estudiante e on p.estudiante_id = e.estudiante_id
            left join plazas_becas pl on p.plaza_id = p.plaza_id
            left join estado es on p.estado_id = es.estado_id
            WHERE
                1 = 1

            ORDER BY e.`estudiante_apellidos` asc, e.`estudiante_nombre` asc
        ")->result_array();

        return $postulante;
    }
}
