<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Postulante_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get postulante by postulante_id
     */
    function get_postulante($postulante_id)
    {
        return $this->db->get_where('postulante',array('postulante_id'=>$postulante_id))->row_array();
    }
        
    /*
     * Get all postulante
     */
    function get_all_postulante()
    {
        $this->db->order_by('postulante_id', 'desc');
        return $this->db->get('postulante')->result_array();
    }
        
    /*
     * function to add new postulante
     */
    function add_postulante($params)
    {
        $this->db->insert('postulante',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update postulante
     */
    function update_postulante($postulante_id,$params)
    {
        $this->db->where('postulante_id',$postulante_id);
        return $this->db->update('postulante',$params);
    }
    
    /*
     * function to delete postulante
     */
    function delete_postulante($postulante_id)
    {
        return $this->db->delete('postulante',array('postulante_id'=>$postulante_id));
    }
    /*
     * Get all postulante y nombre del postulante
     */
    function get_all_postulante_estudiante($filtrar, $filtro)
    {
        $postulante = $this->db->query("
            SELECT
                p.*, e.estudiante_nombre, e.estudiante_apellidos, e.estudiante_carrera, pl.plaza_cantidad,
                b.beca_nombre, es.estado_color, es.estado_descripcion, c.convocatoria_titulo,
                c.convocatoria_descripcion, g.gestion_descripcion, b.beca_id, sp.solunidad_id, cn.contrato_id
            FROM
                `postulante` p
            left join estudiante e on p.estudiante_id = e.estudiante_id
            left join plazas_becas pl on p.plaza_id = pl.plaza_id
            left join beca b on pl.beca_id = b.beca_id
            left join estado es on p.estado_id = es.estado_id
            left join convocatoria c on pl.convocatoria_id = c.convocatoria_id
            left join gestion g on c.gestion_id = g.gestion_id
            left join solunidad_postulante sp on p.postulante_id = sp.postulante_id
            left join contrato cn on p.postulante_id = cn.postulante_id
            WHERE
                1 = 1
                and(e.estudiante_nombre like '%".$filtrar."%' or e.estudiante_apellidos like '%".$filtrar."%'
                   or e.estudiante_ci like '%".$filtrar."%')
                ".$filtro." 
            ORDER BY e.`estudiante_apellidos` asc, e.`estudiante_nombre` asc
        ")->result_array();

        return $postulante;
    }
    /*
     * Get postulante y beca by postulante_id
     */
    function get_thispostulante($postulante_id)
    {
        $postulante = $this->db->query("
            SELECT
                p.*, b.beca_nombre, e.estudiante_apellidos, e.estudiante_nombre, e.estudiante_ci,
                pl.convocatoria_id, c.gestion_id, pl.plaza_id, pl.beca_id,
                g.gestion_descripcion, c.convocatoria_descripcion, c.convocatoria_titulo,
                es.estado_color, es.estado_descripcion
            FROM
                `postulante` p
                left join estudiante e on p.estudiante_id = e.estudiante_id
                left join plazas_becas pl on p.plaza_id = pl.plaza_id
                left join beca b on pl.beca_id = b.beca_id
                left join convocatoria c on pl.convocatoria_id = c.convocatoria_id
                left join gestion g on c.gestion_id = g.gestion_id
                left join estado es on p.estado_id = es.estado_id
            WHERE
                p.postulante_id = $postulante_id
        ")->row_array();
        return $postulante;
    }
}
