<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Publicacion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get publicacion by publicacion_id
     */
    function get_publicacion($publicacion_id)
    {
        return $this->db->get_where('publicacion',array('publicacion_id'=>$publicacion_id))->row_array();
    }
        
    /*
     * Get all publicacion
     */
    function get_all_publicacion()
    {
        $publicacion = $this->db->query("
            SELECT
                p.*, b.beca_nombre, e.estado_descripcion, e.estado_color
            FROM
                `publicacion` p
            left join dube d on p.dube_id = d.dube_id
            left join beca b on p.beca_id = b.beca_id
            left join estado e on p.estado_id = e.estado_id
            WHERE
                1 = 1

            ORDER BY `publicacion_id` DESC
        ")->result_array();

        return $publicacion;
    }
        
    /*
     * function to add new publicacion
     */
    function add_publicacion($params)
    {
        $this->db->insert('publicacion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update publicacion
     */
    function update_publicacion($publicacion_id,$params)
    {
        $this->db->where('publicacion_id',$publicacion_id);
        return $this->db->update('publicacion',$params);
    }
    
    /*
     * function to delete publicacion
     */
    function delete_publicacion($publicacion_id)
    {
        return $this->db->delete('publicacion',array('publicacion_id'=>$publicacion_id));
    }
    /*
     * Get all publicaciones abiertas
     */
    function getall_publicaciones_abiertas()
    {
        $publicacion = $this->db->query("
            SELECT
                p.*, b.beca_nombre, e.estado_descripcion, e.estado_color
            FROM
                `publicacion` p
            left join dube d on p.dube_id = d.dube_id
            left join beca b on p.beca_id = b.beca_id
            left join estado e on p.estado_id = e.estado_id
            WHERE
                p.estado_id = 1

            ORDER BY `publicacion_id` DESC
        ")->result_array();

        return $publicacion;
    }
}
