<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reporte_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    /*
     * Get all solicitud_unidades
     */
    function get_all_solicitud_unidad($gestion_id, $unidad_id)
    {
        $filtro = "";
        if($gestion_id != 0){
            $filtro = " and s.gestion_id = ".$gestion_id;
        }
        if($unidad_id != 0){
            $filtro = $filtro." and s.unidad_id = ".$unidad_id;
        }
        $solicitud_unidad = $this->db->query("
            SELECT
                s.*
            FROM
                `solicitud_unidades` s
            WHERE
                1 = 1
                ".$filtro."
            ORDER BY s.`solicitud_id` DESC
        ")->result_array();

        return $solicitud_unidad;
    }
    
}
