<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Solicitud_unidad_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get solicitud_unidade by solicitud_id
     */
    function get_solicitud_unidad($solicitud_id)
    {
        return $this->db->get_where('solicitud_unidades',array('solicitud_id'=>$solicitud_id))->row_array();
    }
        
    /*
     * Get all solicitud_unidades
     */
    function get_all_solicitud_unidad()
    {
        $solicitud_unidad = $this->db->query("
            SELECT
                s.*, g.gestion_descripcion, u.unidad_nombre, u.unidad_dependencia, u.unidad_responsable
            FROM
                `solicitud_unidades` s
            left join gestion g on s.gestion_id = g.gestion_id
            left join unidad u on s.unidad_id = u.unidad_id
            WHERE
                1 = 1
            ORDER BY s.`solicitud_id` DESC
        ")->result_array();

        return $solicitud_unidad;
    }
        
    /*
     * function to add new solicitud_unidade
     */
    function add_solicitud_unidad($params)
    {
        $this->db->insert('solicitud_unidades',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update solicitud_unidade
     */
    function update_solicitud_unidad($solicitud_id,$params)
    {
        $this->db->where('solicitud_id',$solicitud_id);
        return $this->db->update('solicitud_unidades',$params);
    }
    
    /*
     * function to delete solicitud_unidade
     */
    function delete_solicitud_unidad($solicitud_id)
    {
        return $this->db->delete('solicitud_unidades',array('solicitud_id'=>$solicitud_id));
    }
    /*
     * Get all solicitud_unidades de una gestion
     */
    function get_all_solicitudunidad_gestion($gestion_id)
    {
        $solicitud_unidad = $this->db->query("
            SELECT
                s.*, g.gestion_descripcion, u.unidad_nombre, u.unidad_responsable,
                (s.`solicitud_cantidad_becarios` - count(`ud`.`solunidad_id`)) as cantidad_disponible
            FROM
                `solicitud_unidades` s
            left join gestion g on s.gestion_id = g.gestion_id
            left join unidad u on s.unidad_id = u.unidad_id
            left join `solunidad_postulante` ud on s.solicitud_id = ud.solicitud_id
            WHERE
                s.gestion_id = $gestion_id
            group by s.solicitud_id
            ORDER BY s.`solicitud_id` DESC
        ")->result_array();

        return $solicitud_unidad;
    }
}
