<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Solunidad_postulante_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    } 
    /*
     * function to add new solunidad_postulante
     */
    function add_solunidad_postulante($params)
    {
        $this->db->insert('solunidad_postulante',$params);
        return $this->db->insert_id();
    }
}
