<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Unidad_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get unidad by unidad_id
     */
    function get_unidad($unidad_id)
    {
        return $this->db->get_where('unidad',array('unidad_id'=>$unidad_id))->row_array();
    }
        
    /*
     * Get all unidad
     */
    function get_all_unidad()
    {
        $this->db->order_by('unidad_id', 'desc');
        return $this->db->get('unidad')->result_array();
    }
        
    /*
     * function to add new unidad
     */
    function add_unidad($params)
    {
        $this->db->insert('unidad',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update unidad
     */
    function update_unidad($unidad_id,$params)
    {
        $this->db->where('unidad_id',$unidad_id);
        return $this->db->update('unidad',$params);
    }
    
    /*
     * function to delete unidad
     */
    function delete_unidad($unidad_id)
    {
        return $this->db->delete('unidad',array('unidad_id'=>$unidad_id));
    }
}
